---
permalink: sm-storage/create-asynchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, asynchronous, mirrored, volume 
summary: 'È possibile eseguire il mirroring asincrono di un volume per mantenere i dati nell"array di storage remoto in modo da essere una copia coerente point-in-time dei dati nell"array di storage locale. A tale scopo, creare un gruppo di coerenza mirror per stabilire la relazione di mirroring tra i due array di storage, quindi selezionare il volume primario e il volume secondario che si desidera utilizzare nel mirror.' 
---
= Creare un volume asincrono mirrorato
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il mirroring asincrono di un volume per mantenere i dati nell'array di storage remoto in modo da essere una copia coerente point-in-time dei dati nell'array di storage locale. A tale scopo, creare un gruppo di coerenza mirror per stabilire la relazione di mirroring tra i due array di storage, quindi selezionare il volume primario e il volume secondario che si desidera utilizzare nel mirror.

.Prima di iniziare
* È necessario impostare le seguenti condizioni:
+
** Il servizio Web Services Proxy è in esecuzione.
** SANtricity è in esecuzione sull'host locale tramite una connessione HTTPS.
** Ciascun controller dell'array primario e secondario deve disporre di una porta di gestione Ethernet configurata e deve essere collegato alla rete.
** SANtricity Unified Manager mostra certificati SSL validi per lo storage array. È possibile accettare un certificato autofirmato o installare il proprio certificato di sicurezza utilizzando Unified Manager e accedere al menu:Certificate[Certificate Management] (Gestione certificati).
** Il Gestore di sistema di SANtricity viene avviato da un Gestore unificato.
** È necessario aver individuato i due array di storage tra i quali si desidera eseguire il mirroring dei dati. Quindi, da Unified Manager, selezionare l'array di storage del volume primario e fare clic su *Avvia* per aprire il Gestore di sistema SANtricity basato su browser.


* È necessario conoscere la password per gli array di storage locali e remoti.
* Gli array di storage locali e remoti devono essere collegati tramite un fabric Fibre Channel o un'interfaccia iSCSI.


.A proposito di questa attività
Il processo per eseguire il mirroring asincrono di un volume è una procedura a più fasi:

* <<Fase 1: Creare un gruppo di coerenza mirror o selezionarne uno esistente>>
* <<Fase 2: Selezionare il volume principale>>
* <<Fase 3: Selezionare il volume secondario>>


Un volume può partecipare a una sola relazione di mirroring.



== Fase 1: Creare un gruppo di coerenza mirror o selezionarne uno esistente

[role="lead"]
Si crea un gruppo di coerenza mirror o si seleziona un gruppo esistente per stabilire la relazione di mirroring tra l'array di storage locale e l'array di storage remoto.

.A proposito di questa attività
Il numero di relazioni di gruppo di coerenza mirror e di relazioni di coppia mirrorate che è possibile creare dipende dall'hardware dell'array di storage.

.Fasi
. Eseguire una delle seguenti operazioni per accedere alla sequenza di mirroring asincrono:
+
** Selezionare menu:Storage[Mirroring asincrono > Crea coppia mirrorata].
** Selezionare menu:Storage[Volumes > Copy Services > Mirror a volume asincrone].


. Selezionare un gruppo di coerenza mirror esistente o crearne uno nuovo.
+
Per creare un nuovo gruppo di coerenza mirror, procedere come segue:

+
.. Immettere un nome univoco che descriva meglio i dati sui volumi che verranno mirrorati tra i due array di storage (ad esempio, R&D Data).
.. Selezionare l'array di storage remoto su cui si desidera stabilire una relazione mirror con l'array di storage locale.
+
[NOTE]
====
Se lo storage array remoto è protetto da password, il sistema richiede una password.

====
.. Scegliere se risincronizzare le coppie mirrorate sull'array di storage remoto manualmente o automaticamente.
+
*** *Manuale* -- è necessario aggiornare esplicitamente l'immagine point-in-time secondaria utilizzando l'opzione di menu Manual Resincronization (risincronizzazione manuale). Selezionare questa opzione per avviare manualmente la risincronizzazione per tutte le coppie di mirroring asincrono all'interno del gruppo di mirror asincrono.
*** *Automatico* -- utilizzando il menu a discesa, specificare l'ora dall'inizio dell'aggiornamento precedente all'inizio dell'aggiornamento successivo. Per modificare l'intervallo di sincronizzazione automatica dall'impostazione predefinita di ogni 10 minuti, modificare il valore dell'intervallo, definito in minuti.


.. Fare clic su *Create* (Crea).
+
System Manager crea prima il gruppo di coerenza mirror sull'array di storage locale, quindi crea il gruppo di coerenza mirror sull'array di storage remoto.

+
[NOTE]
====
Se System Manager crea correttamente il gruppo di coerenza mirror sull'array di storage locale, ma non lo crea sull'array di storage remoto, elimina automaticamente il gruppo di coerenza mirror dall'array di storage locale. Se si verifica un errore mentre System Manager sta tentando di eliminare il gruppo di coerenza mirror, è necessario eliminarlo manualmente.

====


. Selezionare *Avanti* e passare a. <<Fase 2: Selezionare il volume principale>>.




== Fase 2: Selezionare il volume principale

[role="lead"]
È necessario selezionare il volume primario che si desidera utilizzare nella relazione mirror e allocare la capacità riservata. Tutti i volumi aggiunti al gruppo di coerenza mirror sull'array di storage locale ricopriranno il ruolo principale nella relazione mirror.

.Fasi
. Selezionare un volume esistente che si desidera utilizzare come volume primario nel mirror, quindi fare clic su *Avanti* per allocare la capacità riservata.
. Allocare la capacità riservata per il volume primario selezionato. Eseguire una delle seguenti operazioni:
+
** *Accettare le impostazioni predefinite* -- utilizzare questa opzione consigliata per assegnare la capacità riservata al volume primario con le impostazioni predefinite.
** *Allocare le proprie impostazioni di capacità riservate per soddisfare le esigenze di storage dei dati relative al mirroring asincrono* -- allocare la capacità riservata utilizzando le seguenti linee guida.
+
*** L'impostazione predefinita per la capacità riservata è il 20% della capacità del volume di base, e di solito questa capacità è sufficiente.
*** La capacità richiesta varia in base alla frequenza e alle dimensioni delle scritture i/o nel volume primario e al tempo necessario per mantenere la capacità.
*** In generale, scegliere una capacità più elevata per la capacità riservata se si verifica una o entrambe le seguenti condizioni:
+
**** Si intende mantenere la coppia mirrorata per un lungo periodo di tempo.
**** Una grande percentuale di blocchi di dati cambierà sul volume primario a causa dell'intensa attività di i/O. Utilizzare dati storici sulle performance o altre utility del sistema operativo per determinare l'attività i/o tipica del volume primario.






. Selezionare *Avanti* e passare a. <<Fase 3: Selezionare il volume secondario>>.




== Fase 3: Selezionare il volume secondario

[role="lead"]
Selezionare il volume secondario che si desidera utilizzare nella relazione di mirroring e allocare la capacità riservata. Tutti i volumi aggiunti al gruppo di coerenza mirror sull'array di storage remoto avranno il ruolo secondario nella relazione mirror.

.A proposito di questa attività
Quando si seleziona un volume secondario sull'array di storage remoto, il sistema visualizza un elenco di tutti i volumi idonei per la coppia mirrorata. I volumi non idonei all'utilizzo non vengono visualizzati nell'elenco.

.Fasi
. Selezionare un volume esistente che si desidera utilizzare come volume secondario nella coppia mirrorata, quindi fare clic su *Avanti* per allocare la capacità riservata.
. Allocare la capacità riservata per il volume secondario selezionato. Eseguire una delle seguenti operazioni:
+
** *Accettare le impostazioni predefinite* -- utilizzare questa opzione consigliata per assegnare la capacità riservata al volume secondario con le impostazioni predefinite.
** *Allocare le proprie impostazioni di capacità riservate per soddisfare le esigenze di storage dei dati relative al mirroring asincrono* -- allocare la capacità riservata utilizzando le seguenti linee guida.
+
*** L'impostazione predefinita per la capacità riservata è il 20% della capacità del volume di base, e di solito questa capacità è sufficiente.
*** La capacità richiesta varia in base alla frequenza e alle dimensioni delle scritture i/o nel volume primario e al tempo necessario per mantenere la capacità.
*** In generale, scegliere una capacità più elevata per la capacità riservata se si verifica una o entrambe le seguenti condizioni:
+
**** Si intende mantenere la coppia mirrorata per un lungo periodo di tempo.
**** Una grande percentuale di blocchi di dati cambierà sul volume primario a causa dell'intensa attività di i/O. Utilizzare dati storici sulle performance o altre utility del sistema operativo per determinare l'attività i/o tipica del volume primario.






. Selezionare *fine* per completare la sequenza di mirroring asincrono.


.Risultati
System Manager esegue le seguenti operazioni:

* Avvia la sincronizzazione iniziale tra lo storage array locale e lo storage array remoto.
* Se il volume sottoposto a mirroring è un volume sottile, solo i blocchi sottoposti a provisioning (capacità allocata anziché capacità riportata) vengono trasferiti al volume secondario durante la sincronizzazione iniziale. In questo modo si riduce la quantità di dati da trasferire per completare la sincronizzazione iniziale.
* Crea la capacità riservata per la coppia mirrorata sull'array di storage locale e sull'array di storage remoto.

