---
settings:
  name: SANtricity 11.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Software SANtricity
    url: "/e-series-santricity-115"
    version-number: '11.5'
  - name: Software SANtricity
    url: "/e-series-santricity"
    version-number: '11.7'
  - name: Software SANtricity
    url: "/e-series-santricity-116"
    version-number: '11.6'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di SANtricity 11.5
    url: "/index.html"
  - section: sm-interface
  - section: sm-storage
  - section: sm-mirroring
  - section: sm-hardware
  - section: sm-settings
  - section: sm-support
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
