---
permalink: sm-hardware/configure-iser-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, iser, infiniband, ports 
summary: 'Se il controller include una porta iSER su InfiniBand, è possibile configurare la connessione di rete all"host. Le impostazioni di configurazione sono disponibili nella pagina hardware o nella pagina sistema.' 
---
= Configurare iSER su porte InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una porta iSER su InfiniBand, è possibile configurare la connessione di rete all'host. Le impostazioni di configurazione sono disponibili nella pagina hardware o nella pagina sistema.

.Prima di iniziare
* Il controller deve includere una porta iSER su InfiniBand; in caso contrario, le impostazioni iSER su InfiniBand non sono disponibili in System Manager.
* È necessario conoscere l'indirizzo IP della connessione host.


.A proposito di questa attività
È possibile accedere alla configurazione di iSER su InfiniBand dalla pagina *hardware* o dal menu:Impostazioni[sistema]. Questa attività descrive come configurare le porte dalla pagina *hardware*.

[NOTE]
====
Le impostazioni e le funzioni di iSER su InfiniBand vengono visualizzate solo se il controller dello storage array include una porta iSER su InfiniBand.

====
.Fasi
. Selezionare *hardware*.
. Se la figura mostra i dischi, fare clic su *Mostra retro dello shelf*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con la porta iSER su InfiniBand che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configura iSER su porte InfiniBand*.
+
Viene visualizzata la finestra di dialogo *Configure iSER over InfiniBand Ports* (Configura porte iSER su InfiniBand).

. Nell'elenco a discesa, selezionare la porta HIC che si desidera configurare, quindi immettere l'indirizzo IP dell'host.
. Fare clic su *Configura*.
. Completare la configurazione, quindi reimpostare iSER sulla porta InfiniBand facendo clic su *Sì*.

