---
permalink: sm-settings/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: 'Se il controller include una connessione per NVMe su RoCE (RDMA over Converged Ethernet), è possibile configurare le impostazioni della porta NVMe dalla pagina hardware o dalla pagina sistema.' 
---
= Configurare NVMe sulle porte RoCE
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una connessione per NVMe su RoCE (RDMA over Converged Ethernet), è possibile configurare le impostazioni della porta NVMe dalla pagina hardware o dalla pagina sistema.

.Prima di iniziare
* Il controller deve includere un NVMe su una porta host RoCE; in caso contrario, le impostazioni NVMe su RoCE non sono disponibili in System Manager.
* È necessario conoscere l'indirizzo IP della connessione host.


.A proposito di questa attività
È possibile accedere alla configurazione NVMe over RoCE dalla pagina *hardware* o dal menu:Impostazioni[sistema]. Questa attività descrive come configurare le porte dalla pagina hardware.

[NOTE]
====
Le impostazioni e le funzioni NVMe over RoCE vengono visualizzate solo se il controller dello storage array include una porta NVMe over RoCE.

====
.Fasi
. Selezionare *hardware*.
. Se la figura mostra i dischi, fare clic su *Mostra retro dello shelf*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con la porta NVMe over RoCE che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configure NVMe over RoCE ports* (Configura NVMe su porte RoCE).
+
Viene visualizzata la finestra di dialogo Configure NVMe over RoCE Ports (Configura porte NVMe su RoCE).

. Nell'elenco a discesa, selezionare la porta HIC che si desidera configurare.
. Fare clic su *Avanti*.
+
Per visualizzare tutte le impostazioni della porta, fare clic sul collegamento *Mostra altre impostazioni della porta* a destra della finestra di dialogo.

+
.Dettagli campo
[%collapsible]
====
|===
| Impostazione della porta | Descrizione 


 a| 
Velocità della porta ethernet configurata
 a| 
Selezionare la velocità che corrisponde alla velocità del modulo SFP sulla porta.



 a| 
Attiva IPv4 / attiva IPv6
 a| 
Selezionare una o entrambe le opzioni per abilitare il supporto per le reti IPv4 e IPv6.


NOTE: Se si desidera disattivare l'accesso alla porta, deselezionare entrambe le caselle di controllo.



 a| 
Dimensione MTU (disponibile facendo clic su Mostra altre impostazioni della porta).
 a| 
Se necessario, inserire una nuova dimensione in byte per l'unità di trasmissione massima (MTU).

La dimensione massima predefinita dell'unità di trasmissione (MTU) è di 1500 byte per frame. Immettere un valore compreso tra 1500 e 9000.

|===
====
+
Se si seleziona Enable IPv4 (attiva IPv4), dopo aver fatto clic su Next (Avanti) viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv4. Se si seleziona Enable IPv6 (attiva IPv6), viene visualizzata una finestra di dialogo per la selezione delle impostazioni IPv6 dopo aver fatto clic su Next (Avanti). Se sono state selezionate entrambe le opzioni, viene visualizzata prima la finestra di dialogo per le impostazioni IPv4, quindi dopo aver fatto clic su Avanti, viene visualizzata la finestra di dialogo per le impostazioni IPv6.

. Configurare le impostazioni IPv4 e/o IPv6, automaticamente o manualmente.
+
.Dettagli campo
[%collapsible]
====
|===
| Impostazione della porta | Descrizione 


 a| 
Ottenere automaticamente la configurazione
 a| 
Selezionare questa opzione per ottenere la configurazione automaticamente.



 a| 
Specificare manualmente la configurazione statica
 a| 
Selezionare questa opzione, quindi inserire un indirizzo statico nei campi. (Se lo si desidera, è possibile tagliare e incollare gli indirizzi nei campi). Per IPv4, includere la subnet mask di rete e il gateway. Per IPv6, includere l'indirizzo IP instradabile e l'indirizzo IP del router.

|===
====
. Fare clic su *fine*.

