---
permalink: sm-settings/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, infiniband, ports 
summary: Se il controller include una connessione NVMe su InfiniBand, è possibile configurare le impostazioni della porta NVMe dalla pagina hardware o dalla pagina sistema. 
---
= Configurare NVMe sulle porte InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il controller include una connessione NVMe su InfiniBand, è possibile configurare le impostazioni della porta NVMe dalla pagina hardware o dalla pagina sistema.

.Prima di iniziare
* Il controller deve includere una porta host NVMe over InfiniBand; in caso contrario, le impostazioni NVMe over InfiniBand non sono disponibili in System Manager.
* È necessario conoscere l'indirizzo IP della connessione host.


.A proposito di questa attività
È possibile accedere alla configurazione NVMe su InfiniBand dalla pagina *hardware* o dal menu:Impostazioni[sistema]. Questa attività descrive come configurare le porte dalla pagina *hardware*.

[NOTE]
====
Le impostazioni e le funzioni NVMe over InfiniBand vengono visualizzate solo se il controller dello storage array include una porta NVMe over InfiniBand.

====
.Fasi
. Selezionare *hardware*.
. Se la figura mostra i dischi, fare clic su *Mostra retro dello shelf*.
+
Il grafico cambia per mostrare i controller invece dei dischi.

. Fare clic sul controller con la porta NVMe over InfiniBand che si desidera configurare.
+
Viene visualizzato il menu di scelta rapida del controller.

. Selezionare *Configura NVMe su porte InfiniBand*.
+
Viene visualizzata la finestra di dialogo *Configure NVMe over InfiniBand Ports* (Configura porte NVMe su InfiniBand).

. Nell'elenco a discesa, selezionare la porta HIC che si desidera configurare, quindi immettere l'indirizzo IP dell'host.
. Fare clic su *Configura*.
. Completare la configurazione, quindi reimpostare NVMe sulla porta InfiniBand facendo clic su *Sì*.

