---
permalink: sm-settings/delete-trusted-certificates.html 
sidebar: sidebar 
keywords: delete, trusted, certificates 
summary: 'È possibile eliminare qualsiasi certificato importato dall"utente.' 
---
= Eliminare i certificati attendibili
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare qualsiasi certificato importato dall'utente.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* Se si sta aggiornando un certificato attendibile con una nuova versione, il certificato aggiornato deve essere importato prima di eliminare il vecchio certificato.


[CAUTION]
====
Se si elimina un certificato utilizzato per autenticare i certificati di gestione dell'array di storage o il server LDAP, si potrebbe perdere l'accesso al sistema prima di importare un certificato sostitutivo.

====
.A proposito di questa attività
Questa attività descrive come eliminare i certificati importati dall'utente. Impossibile eliminare i certificati predefiniti.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Selezionare la scheda *Trusted*.
+
La tabella mostra i certificati attendibili dell'array di storage.

. Nella tabella, selezionare il certificato che si desidera rimuovere.
. Fare clic sul menu:attività non comuni[Elimina].
+
Viene visualizzata la finestra di dialogo Conferma eliminazione certificato attendibile.

. Tipo `delete` Nel campo, quindi fare clic su *Delete* (Elimina).

