---
permalink: sm-settings/how-do-i-know-what-certificates-need-to-be-uploaded-to-system-manager.html 
sidebar: sidebar 
keywords: how, what, know, certificates, need, uploaded, system manager 
summary: 'Per la gestione esterna delle chiavi, vengono importati due tipi di certificati per l"autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l"una dell"altra.' 
---
= Come è possibile sapere quali certificati devono essere caricati in System Manager?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la gestione esterna delle chiavi, vengono importati due tipi di certificati per l'autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l'una dell'altra.

Un certificato client convalida i controller dello storage array, in modo che il server di gestione delle chiavi possa considerare attendibili i propri indirizzi IP. Per ottenere un certificato client, è necessario completare una CSR per l'array di storage e caricarla sul server di gestione delle chiavi. Dal server, generare un certificato client, quindi utilizzare System Manager per importarlo.

Un certificato del server di gestione delle chiavi convalida il server di gestione delle chiavi, in modo che lo storage array possa fidarsi del proprio indirizzo IP. Per ottenere un certificato del server di gestione delle chiavi, è necessario generarlo dal server di gestione delle chiavi.
