---
permalink: sm-settings/import-trusted-certificates-for-controllers-acting-as-client.html 
sidebar: sidebar 
keywords: import, trusted, certificates, controllers 
summary: 'Dopo aver ricevuto i certificati digitali da un"autorità di certificazione (CA), è possibile importare la catena di certificati (intermedia e principale) per i controller.' 
---
= Importazione di certificati attendibili per i controller
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver ricevuto i certificati digitali da un'autorità di certificazione (CA), è possibile importare la catena di certificati (intermedia e principale) per i controller.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* È stata generata una richiesta di firma del certificato (file CSR) e inviata alla CA.
* La CA ha restituito file di certificato attendibili.
* I file dei certificati vengono installati nel sistema locale.


.A proposito di questa attività
Questa attività descrive come caricare i certificati attendibili per i controller dell'array di storage.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Dalla scheda *Trusted*, selezionare *Import* (Importa).
+
Viene visualizzata una finestra di dialogo per l'importazione dei file di certificato attendibili.

. Fare clic su *Browse* (Sfoglia) per selezionare i file di certificato per i controller.
+
I nomi dei file vengono visualizzati nella finestra di dialogo.

. Fare clic su *Importa*.


.Risultati
I file vengono caricati e validati.

.Al termine
Importare il certificato di gestione.
