---
permalink: sm-settings/reset-management-certificates.html 
sidebar: sidebar 
keywords: reset, management, certificates 
summary: 'È possibile riportare i certificati di gestione sull"array di storage allo stato autofirmato di fabbrica.' 
---
= Reimpostare i certificati di gestione
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile riportare i certificati di gestione sull'array di storage allo stato autofirmato di fabbrica.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* I certificati devono essere importati in precedenza.


.A proposito di questa attività
La reimpostazione dei certificati di gestione sullo storage array elimina i certificati di gestione correnti da ciascuno dei controller. Una volta ripristinati i certificati, i controller tornano a utilizzare certificati autofirmati.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Dalla scheda *Array Management* (Gestione array), selezionare *Reset* (Ripristina).
+
Viene visualizzata la finestra di dialogo *Conferma ripristino certificati di gestione*.

. Tipo `reset` Nel campo e fare clic su *Reset*.


.Risultati
Dopo l'aggiornamento del browser, i controller tornano a utilizzare certificati autofirmati. Di conseguenza, il sistema richiede agli utenti di accettare manualmente il certificato autofirmato per le sessioni.
