---
permalink: sm-settings/step-2-import-certificates-for-key-management-server.html 
sidebar: sidebar 
keywords: import, key, management, server, certificates 
summary: 'Per la gestione esterna delle chiavi, si importano certificati per l"autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l"una dell"altra. Esistono due tipi di certificati: Il certificato client convalida i controller, mentre il certificato del server di gestione delle chiavi convalida il server.' 
---
= Importazione dei certificati del server di gestione delle chiavi
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la gestione esterna delle chiavi, si importano certificati per l'autenticazione tra lo storage array e il server di gestione delle chiavi in modo che le due entità possano fidarsi l'una dell'altra. Esistono due tipi di certificati: Il certificato client convalida i controller, mentre il certificato del server di gestione delle chiavi convalida il server.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* È disponibile un certificato client per lo storage array.
+
[NOTE]
====
Un certificato client convalida i controller dello storage array, in modo che il server di gestione delle chiavi possa considerare attendibili i propri indirizzi IP. Per ottenere un certificato client, è necessario completare una CSR per l'array di storage e caricarla sul server di gestione delle chiavi. Dal server, generare un certificato client.

====
* Il certificato del server di gestione delle chiavi è disponibile.
+
[NOTE]
====
Un certificato del server di gestione delle chiavi convalida il server, in modo che lo storage array possa fidarsi del proprio indirizzo IP. Per ottenere un certificato del server di gestione delle chiavi, è necessario generarlo dal server di gestione delle chiavi.

====


.A proposito di questa attività
Questa attività descrive come caricare i file di certificato per l'autenticazione tra i controller degli array di storage e il server di gestione delle chiavi.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Dalla scheda *Key Management* (Gestione chiavi), selezionare *Import* (Importa).
+
Viene visualizzata una finestra di dialogo per l'importazione dei file dei certificati.

. Fare clic sui pulsanti *Browse* per selezionare i file.
+
I nomi dei file vengono visualizzati nella finestra di dialogo.

. Fare clic su *Importa*.
+
I file vengono caricati e validati.


