---
permalink: sm-settings/view-nvme-over-fabrics-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, over, fabrics, statistics 
summary: È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array. 
---
= Visualizza le statistiche NVMe over Fabrics
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i dati relativi alle connessioni NVMe over Fabrics allo storage array.

.A proposito di questa attività
System Manager mostra questi tipi di statistiche NVMe over Fabrics. Tutte le statistiche sono di sola lettura e non possono essere impostate.

* *NVMe Subsystem statistics* -- fornisce statistiche per il controller NVMe, inclusi timeout e errori di connessione.
* *RDMA Interface statistics* -- fornisce statistiche per l'interfaccia RDMA, incluse informazioni sui pacchetti ricevuti e trasmessi.


È possibile visualizzare ciascuna di queste statistiche come statistiche raw o come statistiche baseline. Le statistiche raw sono tutte le statistiche raccolte dall'avvio dei controller. Le statistiche di riferimento sono statistiche point-in-time raccolte dall'ora di riferimento impostata.

È possibile accedere alle statistiche NVMe over Fabrics dalla pagina System (sistema) (menu:Impostazioni[sistema]) o dalla pagina Support (supporto). Queste istruzioni descrivono come accedere alle statistiche dalla pagina di supporto.

.Fasi
. Selezionare menu:scheda Support[Support Center > Diagnostics].
. Selezionare *View NVMe over Fabrics Statistics* (Visualizza statistiche NVMe over Fabrics).
. Per impostare la linea di base, fare clic su *Set new baseline* (Imposta nuova linea di base).
+
L'impostazione della linea di base consente di impostare un nuovo punto di partenza per la raccolta delle statistiche. La stessa linea di base viene utilizzata per tutte le statistiche NVMe.


