---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: view, imported, certificate, information 
summary: 'Dalla pagina certificati, è possibile visualizzare il tipo di certificato, l"autorità di emissione e l"intervallo di date valido dei certificati importati in precedenza.' 
---
= Visualizzare le informazioni sul certificato importato
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina certificati, è possibile visualizzare il tipo di certificato, l'autorità di emissione e l'intervallo di date valido dei certificati importati in precedenza.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.


.A proposito di questa attività
Questa attività descrive come visualizzare le informazioni relative ai certificati installati dall'utente o preinstallati.

.Fasi
. Selezionare il menu:Impostazioni[certificati].
. Selezionare una delle schede per visualizzare informazioni sui certificati di gestione per i controller, i certificati attendibili e i certificati per un server di gestione delle chiavi.
+
[cols="25h,~"]
|===
| Scheda | Descrizione 


 a| 
Gestione degli array
 a| 
Visualizza informazioni su tutti i certificati server importati per i controller.



 a| 
Affidabile
 a| 
Visualizza informazioni su tutti i certificati attendibili (root) importati per i controller. Utilizzare il campo del filtro sotto *Mostra certificati...* per visualizzare i certificati installati dall'utente o preinstallati.

** *Installato dall'utente*. Certificati caricati da un utente nell'array di storage (inclusi certificati attendibili, certificati LDAPS e certificati Identity Federation).
** *Preinstallato*. Certificati inclusi con lo storage array.




 a| 
Gestione delle chiavi
 a| 
Visualizza informazioni su tutti i certificati di gestione (firmati) importati per un server di gestione delle chiavi esterno.

|===

