---
permalink: sm-settings/what-is-cache-block-size.html 
sidebar: sidebar 
keywords: what, cache, block, size 
summary: Il controller dello storage array organizza la cache in blocchi, che sono blocchi di memoria che possono essere di 4, 8, 16 o 32 KiB. Tutti i volumi sul sistema storage condividono lo stesso spazio cache; pertanto, i volumi possono avere una sola dimensione del blocco cache. 
---
= Che cos'è la dimensione del blocco della cache?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il controller dell'array di storage organizza la cache in "blocchi", ovvero blocchi di memoria che possono essere di 4, 8, 16 o 32 KiB. Tutti i volumi sul sistema storage condividono lo stesso spazio cache; pertanto, i volumi possono avere una sola dimensione del blocco cache.

[NOTE]
====
I blocchi della cache non corrispondono ai blocchi da 512 byte utilizzati dal sistema a blocchi logici dei dischi.

====
Le applicazioni utilizzano blocchi di dimensioni diverse, che possono avere un impatto sulle performance dello storage. Per impostazione predefinita, la dimensione del blocco in System Manager è 8 KiB, ma è possibile impostare il valore su 4, 8, 16 o 32 KiB. Una dimensione inferiore è una buona scelta per file system o applicazioni di database. Una dimensione maggiore è una buona scelta per le applicazioni che richiedono un grande trasferimento di dati, l'i/o sequenziale o un'elevata larghezza di banda, come ad esempio le applicazioni multimediali.
